### ISSUE TITLE
Add tab complete to replay commands

### ISSUE THREAD

**Issue by Josh65-2201** [Jumper251/AdvancedReplay#165] opened 2024-05-23 20:18 UTC
Only one the replay file names it has this but no other command

**Comment by Josh65-2201** [comment] 2024-05-28 13:56
Everything under `/replay` then press tab, It wont add anything to the command or have Minecraft's command preview

**Comment by Budderman18** [comment] 2024-05-29 02:35
im not sure what you're talking about, AR has tab-completion.

**Comment by Josh65-2201** [comment] 2024-05-30 18:51
It doesn't work for me then. Is there a separate Luckperms permission that it isn't showing? Since it can run the commands if I get them from the help page. I'm running 1.20.1 Paper build 198

**Comment by Jumper251** [comment] 2024-06-16 17:09
Do you get any error messages when trying to tab complete or on startup?

**Comment by Josh65-2201** [comment] 2024-06-16 17:12
There's nothing when trying to tab complete. The only info on start up is the plugin loading and
`[16:38:15 WARN]: Legacy plugin AdvancedReplay v1.8.5 does not specify an api-version.`

**Comment by Jumper251** [comment] 2024-06-24 15:53
There should be no problem with tab completion. 
Apart from this, is AdvancedReplay working as expected?
Do you have tab completion problems in any other plugins?

**Comment by Josh65-2201** [comment] 2024-06-24 15:55
Yes it work as it should, No other plugins don't have an issue

**Comment by Jumper251** [comment] 2024-06-24 16:14
Is there anything else you can think of how to reproduce this?
You seem to be the first one to report this issue.

**Comment by Josh65-2201** [comment] 2024-06-25 15:01
Unless there some permission I'm missing currently using the below, this is the only one and first time having this issue.
![image](https://github.com/Jumper251/AdvancedReplay/assets/26977075/8fd22a34-96e6-4b0d-9cfb-02366d0ef5c3)

**Comment by Jumper251** [comment] 2024-06-25 16:59
It looks like there was an error with tab completion when using the direct permission for each command instead of `replay.command.*`. 
This should be fixed in 93b2997 (https://github.com/Jumper251/AdvancedReplay/actions/runs/9666307744)

**Closed by Jumper251** 2024-06-25 16:59 UTC
