### ISSUE TITLE
Plugin cannot be replayed

### ISSUE THREAD

**Issue by YimingZhanshen** [Jumper251/AdvancedReplay#122] opened 2023-01-01 19:09 UTC
`[03:00:06 WARN]: [AdvancedReplay] Task #89053 for AdvancedReplay v1.8.2 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
        at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:289) ~[ProtocolLib-5.0.0-SNAPSHOT.jar:?]
        at com.comphenix.packetwrapper.WrapperPlayServerPlayerInfo.setAction(WrapperPlayServerPlayerInfo.java:45) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.utils.entities.PacketNPC.getInfoAddPacket(PacketNPC.java:289) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.utils.entities.PacketNPC.spawn(PacketNPC.java:101) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.ReplayingUtils.spawnNPC(ReplayingUtils.java:474) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.ReplayingUtils.handleAction(ReplayingUtils.java:85) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.Replayer.executeTick(Replayer.java:144) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.replaying.Replayer.start(Replayer.java:101) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.Replay.startReplay(Replay.java:69) ~[Replay.jar:?]
        at me.jumper251.replay.replaysystem.Replay.lambda$play$0(Replay.java:60) ~[Replay.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-366]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-366]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-366]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-366]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-366]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-366]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-366]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]`

**Comment by DiscowZombie** [comment] 2023-01-02 13:24
Duplicate of https://github.com/Jumper251/AdvancedReplay/issues/121.

**Closed** 2023-01-16 19:49 UTC
